# Generated by Django 4.2.4 on 2023-10-06 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_perfilusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
