# Generated by Django 4.2.7 on 2023-11-17 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0004_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='comuna',
            field=models.CharField(blank=True, default='No Ingresado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='region',
            field=models.CharField(blank=True, default='No Ingresado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, default='NO Ingresado', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(default='sinfoto.jpg', upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('codigo_factura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=90, null=True)),
                ('monto_producto', models.IntegerField(blank=True, default=1, null=True)),
                ('precio_producto', models.IntegerField()),
                ('fecha_factura', models.DateTimeField(auto_now=True)),
                ('estado_factura', models.CharField(blank=True, default='Pendiente', max_length=40, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.perfilusuario')),
            ],
        ),
    ]
