# Generated by Django 4.2.6 on 2023-11-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0004_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(default='sinfoto.jpg', upload_to='images/'),
        ),
    ]
