# Generated by Django 4.2.6 on 2023-11-03 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0005_productos_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('codigo_factura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=90, null=True)),
                ('precio_producto', models.IntegerField()),
                ('fecha_factura', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.perfilusuario')),
            ],
        ),
    ]
